"""
Executive Token API Router for EnteBus.

Provides endpoints for managing executive access tokens, including creation,
refresh, deletion, and retrieval. Uses Pydantic schemas for
input validation and structured output.
"""

from datetime import datetime, timedelta
from enum import StrEnum
from typing import Optional
from fastapi import APIRouter, Depends, Query, Response, status, Form
from fastapi.encoders import jsonable_encoder
from pydantic import BaseModel, Field
from fastapi.security import OAuth2PasswordRequestForm

from app.api.bearer import oauth2_executive
from app.src.db import ExecutiveToken, SessionLocal
from app.src import exceptions
from app.src.enums import PlatformType, GrantType, OrderIn
from app.src.filters import (
    CreatedOnFilter,
    IDFilter,
    PaginationFilter,
    ClientDataFilter,
)
from app.src.openobserve import log_event
from app.src.permissions.executive import PermissionPath
from app.src.urls import URL_EXECUTIVE_TOKEN
from app.src.constants import (
    MAX_ACCESS_TOKEN_VALIDITY,
    MAX_EXECUTIVE_TOKENS,
    MAX_REFRESH_TOKEN_VALIDITY,
)
from app.src.validators import (
    verify_permission,
    verify_token,
    authenticate_executive,
    validate_and_revoke_refresh_token,
)
from app.src.functions import (
    apply_created_on_filters,
    apply_id_filters,
    apply_client_data_filters,
    cleanup_old_tokens,
    enum_str,
    fuse_exception_responses,
    get_request_info,
    get_executive_roles,
)

route_executive = APIRouter()


## Output Schema
class MaskedExecutiveTokenSchema(BaseModel):
    """Schema for executive token response without revealing the tokens."""

    id: int
    executive_id: int
    expires_in: int
    refresh_before: datetime
    platform_type: int
    client_details: Optional[str]
    created_on: datetime


class ExecutiveTokenSchema(MaskedExecutiveTokenSchema):
    """Schema for executive token response including the tokens."""

    access_token: str
    refresh_token: str
    token_type: Optional[str] = "bearer"


## Input Forms
class CreateForm(BaseModel):
    """Form data for creating a new executive token."""

    platform_type: PlatformType = Field(
        Form(description=enum_str(PlatformType), default=PlatformType.OTHER)
    )
    client_details: str | None = Field(Form(max_length=1024, default=None))


class UpdateForm(BaseModel):
    """Form data for refreshing an executive token."""

    refresh_token: str = Field(Form())
    grant_type: GrantType = Field(
        Form(description=enum_str(GrantType), default=GrantType.REFRESH_TOKEN)
    )


class LogoutForm(BaseModel):
    """Form data for logging out with an executive token."""

    token: str = Field(Form(description="Access or refresh token"))


## Query Parameters
class OrderBy(StrEnum):
    """Enum for ordering results."""

    ID = "id"
    CREATED_ON = "created_on"


class QueryParams(ClientDataFilter, CreatedOnFilter, IDFilter, PaginationFilter):
    """Query parameters for executive token endpoints."""

    executive_id: int | None = Field(Query(default=None))
    order_by: OrderBy = Field(Query(default=OrderBy.ID, description=enum_str(OrderBy)))
    order_in: OrderIn = Field(
        Query(default=OrderIn.DESCENDING, description=enum_str(OrderIn))
    )


# ---------------------------------------------------------------------------
## API endpoints [Executive]
# ---------------------------------------------------------------------------
@route_executive.post(
    URL_EXECUTIVE_TOKEN,
    summary="Create executive token",
    tags=["Token"],
    response_model=ExecutiveTokenSchema,
    responses=fuse_exception_responses(
        [
            exceptions.InactiveAccount(),
            exceptions.InvalidCredentials(),
            exceptions.InvalidGrantType(),
        ]
    ),
    description=(
        f"""
            **Issue a new access token for an executive after validating credentials.**    
            - Verify the username and password.    
            - Ensure the executive account is in `active status` before allowing token creation.    
            - Maintain a limit of `{MAX_EXECUTIVE_TOKENS}` active tokens per executive to control token rotation.    
            - Generate a new Executive Token with a pair of access and refresh tokens.    
            - The `expires_in` indicates the number of seconds until the access token expires, the maximum allowed access token validity is `{(timedelta(seconds=MAX_ACCESS_TOKEN_VALIDITY)).seconds // 60}` minutes.    
            - The `refresh_before` indicates the datetime when the refresh token expires, the maximum allowed refresh token validity is `{(timedelta(seconds=MAX_REFRESH_TOKEN_VALIDITY)).days}` days.    
            - A new access token can be generated by using the refresh token before it expires.    
        """
    ),
)
async def create_executive_token_for_executive(
    form_param: CreateForm = Depends(),
    credentials: OAuth2PasswordRequestForm = Depends(),
    request_info=Depends(get_request_info),
):
    try:
        session = SessionLocal()
        executive = authenticate_executive(session, credentials)

        # Remove excess tokens
        cleanup_old_tokens(
            session,
            ExecutiveToken,
            ExecutiveToken.executive_id == executive.id,
            MAX_EXECUTIVE_TOKENS - 1,
        )

        # Create new token
        token = ExecutiveToken(
            executive_id=executive.id,
            platform_type=form_param.platform_type,
            client_details=form_param.client_details,
        )
        session.add(token)
        session.commit()
        session.refresh(token)

        token_data = jsonable_encoder(token)
        token_log_data = token_data.copy()
        token_log_data.pop(ExecutiveToken.access_token.name)
        token_log_data.pop(ExecutiveToken.refresh_token.name)
        log_event(token, request_info, token_log_data)
        return token_data
    except Exception as e:
        exceptions.handle(e)
    finally:
        session.close()


@route_executive.post(
    f"{URL_EXECUTIVE_TOKEN}/refresh",
    summary="Refresh executive token",
    tags=["Token"],
    response_model=ExecutiveTokenSchema,
    responses=fuse_exception_responses(
        [
            exceptions.InvalidToken(),
            exceptions.UnknownValue(ExecutiveToken.refresh_token),
            exceptions.InvalidGrantType(),
        ]
    ),
    description=(
        f"""
            **Refresh an executive's access token using a valid refresh token.**    
            - Verify the provided refresh token exists in the database.    
            - Invalidate the current refresh token.    
            - Generate a new `Executive Token` with a pair of access and refresh tokens.    
            - The `expires_in` indicates the number of seconds until the access token expires, the maximum allowed access token validity is `{(timedelta(seconds=MAX_ACCESS_TOKEN_VALIDITY)).seconds // 60}` minutes.    
            - The `refresh_before` indicates the datetime when the refresh token expires, the maximum allowed refresh token validity is `{(timedelta(seconds=MAX_REFRESH_TOKEN_VALIDITY)).days}` days.    
            - A new access token can be generated by using the refresh token before it expires.    
        """
    ),
)
async def refresh_executive_token_for_executive(
    form_param: UpdateForm = Depends(),
    request_info=Depends(get_request_info),
):
    try:
        session = SessionLocal()
        # Validate and revoke the old refresh token
        token = validate_and_revoke_refresh_token(session, ExecutiveToken, form_param)
        # Create new token
        refresh_token = ExecutiveToken(
            executive_id=token.executive_id,
            platform_type=token.platform_type,
            client_details=token.client_details,
        )
        session.add(refresh_token)
        session.flush()

        # Remove excess tokens
        cleanup_old_tokens(
            session,
            ExecutiveToken,
            ExecutiveToken.executive_id == token.executive_id,
            MAX_EXECUTIVE_TOKENS,
        )
        session.commit()
        session.refresh(refresh_token)

        token_data = jsonable_encoder(refresh_token)
        token_log_data = token_data.copy()
        token_log_data.pop(ExecutiveToken.access_token.name)
        token_log_data.pop(ExecutiveToken.refresh_token.name)
        log_event(token, request_info, token_log_data)
        return token_data
    except Exception as e:
        exceptions.handle(e)
    finally:
        session.close()


@route_executive.post(
    f"{URL_EXECUTIVE_TOKEN}/revoke",
    summary="Revoke executive token",
    tags=["Token"],
    responses=fuse_exception_responses([exceptions.InvalidToken()]),
    description=(
        """
            **Revokes an access token or refresh token associated with the executive.**    
            - Executive must have a valid access token.    
            - Revokes the token (access or refresh) specified in the request body.    
            - If the token is invalid, doesn't belong to the executive, or is already revoked, the operation is silently ignored.    
        """
    ),
)
async def revoke_executive_token_for_executive(
    form_param: LogoutForm = Depends(),
    access_token=Depends(oauth2_executive),
    request_info=Depends(get_request_info),
):
    try:
        session = SessionLocal()
        token = verify_token(session, ExecutiveToken, access_token)

        token_to_revoke = (
            session.query(ExecutiveToken)
            .filter(ExecutiveToken.executive_id == token.executive_id)
            .filter(
                (ExecutiveToken.access_token == form_param.token)
                | (ExecutiveToken.refresh_token == form_param.token)
            )
            .filter(ExecutiveToken.is_revoked.is_(False))
            .first()
        )
        if token_to_revoke:
            token_to_revoke.is_revoked = True
            session.commit()
            session.refresh(token_to_revoke)

            token_log_data = jsonable_encoder(token_to_revoke)
            token_log_data.pop(ExecutiveToken.access_token.name)
            token_log_data.pop(ExecutiveToken.refresh_token.name)
            log_event(token, request_info, token_log_data)

        return Response(status_code=status.HTTP_200_OK)
    except Exception as e:
        exceptions.handle(e)
    finally:
        session.close()


@route_executive.delete(
    f"{URL_EXECUTIVE_TOKEN}/{{id}}",
    summary="Delete executive token",
    tags=["Token"],
    status_code=status.HTTP_204_NO_CONTENT,
    responses=fuse_exception_responses(
        [exceptions.InvalidToken(), exceptions.NoPermission()]
    ),
    description=(
        """
            **Deletes an access token associated with an executive account.**    
            - Executive must have a valid access token.    
            - Executives can delete their own tokens without additional permissions.    
            - To delete another executive's token, the 'executive.token.delete' permission is required.    
            - Trying to delete another executive's token without the required permission will result in a `NoPermission` error.    
            - If the token ID is invalid or already revoked, the operation is silently ignored.    
        """
    ),
)
async def delete_executive_token_for_executive(
    id: int,
    access_token=Depends(oauth2_executive),
    request_info=Depends(get_request_info),
):
    try:
        session = SessionLocal()
        token = verify_token(session, ExecutiveToken, access_token)
        roles = get_executive_roles(session, token)
        has_permission = verify_permission(
            roles,
            PermissionPath.DELETE_EXECUTIVE_TOKEN,
            False,
        )

        token_to_delete = (
            session.query(ExecutiveToken)
            .filter(ExecutiveToken.id == id)
            .filter(ExecutiveToken.is_revoked.is_(False))
            .first()
        )
        if token_to_delete is None:
            return Response(status_code=status.HTTP_204_NO_CONTENT)
        if not has_permission and token_to_delete.executive_id != token.executive_id:
            raise exceptions.NoPermission()

        # Revoke the chosen token
        token_to_delete.is_revoked = True
        session.commit()
        session.refresh(token_to_delete)

        token_log_data = jsonable_encoder(token_to_delete)
        token_log_data.pop(ExecutiveToken.access_token.name)
        token_log_data.pop(ExecutiveToken.refresh_token.name)
        log_event(token, request_info, token_log_data)
        return Response(status_code=status.HTTP_204_NO_CONTENT)
    except Exception as e:
        exceptions.handle(e)
    finally:
        session.close()


@route_executive.get(
    URL_EXECUTIVE_TOKEN,
    summary="Fetch executive token",
    tags=["Token"],
    response_model=list[MaskedExecutiveTokenSchema],
    responses=fuse_exception_responses(
        [exceptions.InvalidToken(), exceptions.NoPermission()]
    ),
    description=(
        """
            **Fetch executive tokens with permission-based filtering.**    
            - If the logged-in executive has `executive.token.fetch` permission, all masked tokens are returned.    
            - If the logged-in executive does not have permission, only masked tokens for the logged-in executive are returned.    
        """
    ),
)
async def fetch_executive_tokens_for_executive(
    query_params: QueryParams = Depends(),
    access_token=Depends(oauth2_executive),
):
    try:
        session = SessionLocal()
        token = verify_token(session, ExecutiveToken, access_token)
        roles = get_executive_roles(session, token)
        has_permission = verify_permission(
            roles,
            PermissionPath.FETCH_EXECUTIVE_TOKEN,
            False,
        )

        query = session.query(ExecutiveToken).filter(ExecutiveToken.is_revoked == False)
        if not has_permission:
            if query_params.executive_id not in (None, token.executive_id):
                raise exceptions.NoPermission()
            # Restrict to only the logged-in executive's tokens
            query = query.filter(ExecutiveToken.executive_id == token.executive_id)

        # Generalized filters
        query = apply_id_filters(query, ExecutiveToken, query_params)
        query = apply_created_on_filters(query, ExecutiveToken, query_params)
        query = apply_client_data_filters(query, ExecutiveToken, query_params)

        # Ordering and pagination
        ordering_attr = getattr(ExecutiveToken, OrderBy(query_params.order_by).value)
        ordering_func = (
            ordering_attr.asc
            if query_params.order_in == OrderIn.ASCENDING
            else ordering_attr.desc
        )
        query = query.order_by(ordering_func())
        query = query.offset(query_params.offset).limit(query_params.limit)

        tokens = query.all()
        return tokens
    except Exception as e:
        exceptions.handle(e)
    finally:
        session.close()
