"""
Operator Token API Router for EnteBus.

Provides an endpoint for managing operator access tokens, including creation.
Uses Pydantic schemas for input validation and structured output.
Endpoints for refresh, deletion, and retrieval are planned for future implementation.
"""

from datetime import datetime, timedelta
from typing import Optional
from fastapi import APIRouter, Depends, Form
from fastapi.encoders import jsonable_encoder
from pydantic import BaseModel, Field
from fastapi.security import OAuth2PasswordRequestForm

from app.src.db import Operator, OperatorToken, SessionLocal
from app.src import exceptions
from app.src.enums import PlatformType
from app.src.openobserve import log_event
from app.src.urls import URL_OPERATOR_TOKEN
from app.src.constants import (
    MAX_ACCESS_TOKEN_VALIDITY,
    MAX_OPERATOR_TOKENS,
    MAX_REFRESH_TOKEN_VALIDITY,
)
from app.src.validators import authenticate_operator
from app.src.functions import (
    cleanup_old_tokens,
    enum_str,
    fuse_exception_responses,
    get_request_info,
)

route_operator = APIRouter()


# Output Schema
class MaskedOperatorTokenSchema(BaseModel):
    """Schema for operator token response without revealing the tokens."""

    id: int
    operator_id: int
    company_id: int
    expires_in: int
    refresh_before: datetime
    platform_type: int
    client_details: Optional[str]
    created_on: datetime


class OperatorTokenSchema(MaskedOperatorTokenSchema):
    """Schema for operator token response including the tokens."""

    access_token: str
    refresh_token: str
    token_type: Optional[str] = "bearer"


# Input Schema.
class CreateForm(BaseModel):
    """Form data for creating a new operator token."""

    company_id: int = Field(Form())
    platform_type: PlatformType = Field(
        Form(description=enum_str(PlatformType), default=PlatformType.OTHER)
    )
    client_details: str | None = Field(Form(max_length=1024, default=None))


# ---------------------------------------------------------------------------
## API endpoints [Operator]
# ---------------------------------------------------------------------------
@route_operator.post(
    URL_OPERATOR_TOKEN,
    tags=["Token"],
    response_model=OperatorTokenSchema,
    responses=fuse_exception_responses(
        [exceptions.InactiveAccount(), exceptions.InvalidCredentials()]
    ),
    description=(
        f"""
            **Issue a new access token for an operator after validating credentials.**     
            - Verify the username and password.     
            - Ensure the operator account is in `active status` before allowing token creation.        
            - Maintain a limit of `{MAX_OPERATOR_TOKENS}` active tokens per operator to control token rotation.               
            - Generate a new Operator Token with a pair of access and refresh tokens.         
            - The `expires_in` indicates the number of seconds until the access token expires, the maximum allowed access token validity is `{(timedelta(seconds=MAX_ACCESS_TOKEN_VALIDITY)).seconds // 60}` minutes.   
            - The `refresh_before` indicates the datetime when the refresh token expires, the maximum allowed refresh token validity is` {(timedelta(seconds=MAX_REFRESH_TOKEN_VALIDITY)).days}` days.   
            - A new access token can be generated by using the refresh token before it expires.     
        """
    ),
)
async def create_token(
    form_param: CreateForm = Depends(),
    credentials: OAuth2PasswordRequestForm = Depends(),
    request_info=Depends(get_request_info),
):
    try:
        session = SessionLocal()
        operator = authenticate_operator(session, Operator, credentials, form_param)

        # Remove excess tokens
        cleanup_old_tokens(
            session,
            OperatorToken,
            OperatorToken.operator_id == operator.id,
            MAX_OPERATOR_TOKENS - 1,
        )

        # Create new token
        token = OperatorToken(
            company_id=form_param.company_id,
            operator_id=operator.id,
            platform_type=form_param.platform_type,
            client_details=form_param.client_details,
        )
        session.add(token)
        session.commit()
        session.refresh(token)

        token_data = jsonable_encoder(token)
        token_log_data = token_data.copy()
        token_log_data.pop(OperatorToken.access_token.name)
        token_log_data.pop(OperatorToken.refresh_token.name)
        log_event(token, request_info, token_log_data)
        return token_data
    except Exception as e:
        exceptions.handle(e)
    finally:
        session.close()
