"""
Vendor Token API Router for EnteBus.

Provides an endpoint for managing vendor access tokens, including creation.
Uses Pydantic schemas for input validation and structured output.
Endpoints for refresh, deletion, and retrieval are planned for future implementation.
"""

from datetime import datetime, timedelta
from typing import Optional
from fastapi import APIRouter, Depends, Form
from fastapi.encoders import jsonable_encoder
from pydantic import BaseModel, Field
from fastapi.security import OAuth2PasswordRequestForm

from app.src.db import Vendor, VendorToken, SessionLocal
from app.src import exceptions
from app.src.enums import PlatformType, GrantType
from app.src.openobserve import log_event
from app.src.urls import URL_VENDOR_TOKEN
from app.src.constants import (
    MAX_ACCESS_TOKEN_VALIDITY,
    MAX_VENDOR_TOKENS,
    MAX_REFRESH_TOKEN_VALIDITY,
)
from app.src.validators import authenticate_vendor, validate_and_revoke_refresh_token
from app.src.functions import (
    cleanup_old_tokens,
    enum_str,
    fuse_exception_responses,
    get_request_info,
)

route_vendor = APIRouter()


# Output Schema
class MaskedVendorTokenSchema(BaseModel):
    """Schema for vendor token response without revealing the tokens."""

    id: int
    vendor_id: int
    business_id: int
    expires_in: int
    refresh_before: datetime
    platform_type: int
    client_details: Optional[str]
    created_on: datetime


class VendorTokenSchema(MaskedVendorTokenSchema):
    """Schema for vendor token response including the tokens."""

    access_token: str
    refresh_token: str
    token_type: Optional[str] = "bearer"


# Input Schema.
class CreateForm(BaseModel):
    """Form data for creating a new vendor token."""

    business_id: int = Field(Form())
    platform_type: PlatformType = Field(
        Form(description=enum_str(PlatformType), default=PlatformType.OTHER)
    )
    client_details: str | None = Field(Form(max_length=1024, default=None))


class UpdateForm(BaseModel):
    """Form data for refreshing a vendor token."""

    refresh_token: str = Field(Form())
    grant_type: GrantType = Field(
        Form(description=enum_str(GrantType), default=GrantType.REFRESH_TOKEN)
    )


# ---------------------------------------------------------------------------
## API endpoints [Vendor]
# ---------------------------------------------------------------------------
@route_vendor.post(
    URL_VENDOR_TOKEN,
    tags=["Token"],
    response_model=VendorTokenSchema,
    responses=fuse_exception_responses(
        [
            exceptions.InactiveAccount(),
            exceptions.InvalidCredentials(),
            exceptions.UnknownValue(Vendor.business_id),
            exceptions.InvalidGrantType(),
        ]
    ),
    description=(
        f"""
            **Issue a new access token for a vendor after validating credentials.**     
            - Verify the username and password.     
            - Ensure the vendor account is in `active status` before allowing token creation.        
            - Maintain a limit of `{MAX_VENDOR_TOKENS}` active tokens per vendor to control token rotation.               
            - Generate a new Vendor Token with a pair of access and refresh tokens.         
            - The `expires_in` indicates the number of seconds until the access token expires, the maximum allowed access token validity is `{(timedelta(seconds=MAX_ACCESS_TOKEN_VALIDITY)).seconds // 60}` minutes.   
            - The `refresh_before` indicates the datetime when the refresh token expires, the maximum allowed refresh token validity is `{(timedelta(seconds=MAX_REFRESH_TOKEN_VALIDITY)).days}` days.   
            - A new access token can be generated by using the refresh token before it expires.     
        """
    ),
)
async def create_token(
    form_param: CreateForm = Depends(),
    credentials: OAuth2PasswordRequestForm = Depends(),
    request_info=Depends(get_request_info),
):
    try:
        session = SessionLocal()
        vendor = authenticate_vendor(session, credentials, form_param)

        # Remove excess tokens
        cleanup_old_tokens(
            session,
            VendorToken,
            VendorToken.vendor_id == vendor.id,
            MAX_VENDOR_TOKENS - 1,
        )

        # Create new token
        token = VendorToken(
            business_id=form_param.business_id,
            vendor_id=vendor.id,
            platform_type=form_param.platform_type,
            client_details=form_param.client_details,
        )
        session.add(token)
        session.commit()
        session.refresh(token)

        token_data = jsonable_encoder(token)
        token_log_data = token_data.copy()
        token_log_data.pop(VendorToken.access_token.name)
        token_log_data.pop(VendorToken.refresh_token.name)
        log_event(token, request_info, token_log_data)
        return token_data
    except Exception as e:
        exceptions.handle(e)
    finally:
        session.close()


@route_vendor.post(
    f"{URL_VENDOR_TOKEN}/refresh",
    tags=["Token"],
    response_model=VendorTokenSchema,
    responses=fuse_exception_responses(
        [
            exceptions.InvalidToken(),
            exceptions.UnknownValue(VendorToken.refresh_token),
            exceptions.InvalidGrantType(),
        ]
    ),
    description=(
        f"""
            **Refresh a vendor's access token using a valid refresh token.**        
            - Verify the provided refresh token exists in the database.     
            - Invalidate the current refresh token.             
            - Generate a new `Vendor Token` with a pair of access and refresh tokens.        
            - The `expires_in` indicates the number of seconds until the access token expires, the maximum allowed access token validity is `{(timedelta(seconds=MAX_ACCESS_TOKEN_VALIDITY)).seconds // 60}` minutes.   
            - The `refresh_before` indicates the datetime when the refresh token expires, the maximum allowed refresh token validity is `{(timedelta(seconds=MAX_REFRESH_TOKEN_VALIDITY)).days}` days.  
            - A new access token can be generated by using the refresh token before it expires.    
        """
    ),
)
async def refresh_token(
    form_param: UpdateForm = Depends(),
    request_info=Depends(get_request_info),
):
    try:
        session = SessionLocal()
        # Validate and revoke the old refresh token
        token = validate_and_revoke_refresh_token(session, VendorToken, form_param)
        # Create new token
        refresh_token = VendorToken(
            vendor_id=token.vendor_id,
            business_id=token.business_id,
            platform_type=token.platform_type,
            client_details=token.client_details,
        )
        session.add(refresh_token)
        session.flush()

        # Remove excess tokens
        cleanup_old_tokens(
            session,
            VendorToken,
            VendorToken.vendor_id == token.vendor_id,
            MAX_VENDOR_TOKENS,
        )
        session.commit()
        session.refresh(refresh_token)

        token_data = jsonable_encoder(refresh_token)
        token_log_data = token_data.copy()
        token_log_data.pop(VendorToken.access_token.name)
        token_log_data.pop(VendorToken.refresh_token.name)
        log_event(token, request_info, token_log_data)
        return token_data
    except Exception as e:
        exceptions.handle(e)
    finally:
        session.close()
