"""added_initial_financial_domain_tables

Revision ID: 0274bb7029f7
Revises: e0ee54589690
Create Date: 2026-02-13 05:12:39.922283

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0274bb7029f7"
down_revision: Union[str, Sequence[str], None] = "e0ee54589690"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bank_name", sa.TEXT(), nullable=False),
        sa.Column("branch_name", sa.TEXT(), nullable=True),
        sa.Column("account_number", sa.TEXT(), nullable=False),
        sa.Column("holder_name", sa.TEXT(), nullable=False),
        sa.Column("ifsc", sa.TEXT(), nullable=False),
        sa.Column("account_type", sa.Integer(), nullable=False),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_geospatial_table(
        "business",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("address", sa.TEXT(), nullable=False),
        sa.Column(
            "location",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_geospatial_index(
        "idx_business_location",
        "business",
        ["location"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )

    op.create_table(
        "wallet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("balance", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "business_bank_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bank_account_id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bank_account_id"], ["bank_account.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["business_id"], ["business.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bank_account_id"),
    )
    op.create_index(
        op.f("ix_business_bank_account_bank_account_id"),
        "business_bank_account",
        ["bank_account_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_business_bank_account_business_id"),
        "business_bank_account",
        ["business_id"],
        unique=False,
    )
    op.create_table(
        "business_wallet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wallet_id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["business.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallet.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_business_wallet_business_id"),
        "business_wallet",
        ["business_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_business_wallet_wallet_id"),
        "business_wallet",
        ["wallet_id"],
        unique=False,
    )
    op.create_table(
        "company_bank_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bank_account_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bank_account_id"], ["bank_account.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bank_account_id"),
    )
    op.create_index(
        op.f("ix_company_bank_account_bank_account_id"),
        "company_bank_account",
        ["bank_account_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_company_bank_account_company_id"),
        "company_bank_account",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "company_wallet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wallet_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallet.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_company_wallet_company_id"),
        "company_wallet",
        ["company_id"],
        unique=True,
    )

    op.create_table(
        "operator_role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column(
            "permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "name"),
    )
    op.create_index(
        op.f("ix_operator_role_company_id"),
        "operator_role",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "vendor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("password", sa.TEXT(), nullable=False),
        sa.Column("gender", sa.Integer(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.TEXT(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("phone_number", sa.TEXT(), nullable=True),
        sa.Column("email_id", sa.TEXT(), nullable=True),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["business.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", "business_id"),
    )
    op.create_index(
        op.f("ix_vendor_business_id"), "vendor", ["business_id"], unique=False
    )
    op.create_table(
        "vendor_role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column(
            "permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["business_id"], ["business.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "name"),
    )
    op.create_index(
        op.f("ix_vendor_role_business_id"), "vendor_role", ["business_id"], unique=False
    )

    op.create_table(
        "operator_role_map",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["operator_id"], ["operator.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["operator_role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "role_id", "operator_id"),
    )
    op.create_index(
        op.f("ix_operator_role_map_company_id"),
        "operator_role_map",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operator_role_map_operator_id"),
        "operator_role_map",
        ["operator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operator_role_map_role_id"),
        "operator_role_map",
        ["role_id"],
        unique=False,
    )

    op.create_table(
        "vendor_image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=128), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_type", sa.String(length=128), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["business.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendor.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vendor_image_business_id"),
        "vendor_image",
        ["business_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_image_vendor_id"), "vendor_image", ["vendor_id"], unique=True
    )
    op.create_table(
        "vendor_role_map",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["business.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["vendor_role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendor.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "role_id", "vendor_id"),
    )
    op.create_index(
        op.f("ix_vendor_role_map_business_id"),
        "vendor_role_map",
        ["business_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_role_map_role_id"), "vendor_role_map", ["role_id"], unique=False
    )
    op.create_index(
        op.f("ix_vendor_role_map_vendor_id"),
        "vendor_role_map",
        ["vendor_id"],
        unique=False,
    )
    op.create_table(
        "vendor_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("access_token", sa.String(length=64), nullable=False),
        sa.Column("refresh_token", sa.String(length=64), nullable=False),
        sa.Column("expires_in", sa.Integer(), nullable=False),
        sa.Column("refresh_before", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("platform_type", sa.Integer(), nullable=True),
        sa.Column("client_details", sa.TEXT(), nullable=True),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["business.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendor.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("access_token"),
        sa.UniqueConstraint("refresh_token"),
    )
    op.create_index(
        op.f("ix_vendor_token_business_id"),
        "vendor_token",
        ["business_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_token_vendor_id"), "vendor_token", ["vendor_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vendor_token_vendor_id"), table_name="vendor_token")
    op.drop_index(op.f("ix_vendor_token_business_id"), table_name="vendor_token")
    op.drop_table("vendor_token")
    op.drop_index(op.f("ix_vendor_role_map_vendor_id"), table_name="vendor_role_map")
    op.drop_index(op.f("ix_vendor_role_map_role_id"), table_name="vendor_role_map")
    op.drop_index(op.f("ix_vendor_role_map_business_id"), table_name="vendor_role_map")
    op.drop_table("vendor_role_map")
    op.drop_index(op.f("ix_vendor_image_vendor_id"), table_name="vendor_image")
    op.drop_index(op.f("ix_vendor_image_business_id"), table_name="vendor_image")
    op.drop_table("vendor_image")

    op.drop_index(op.f("ix_operator_role_map_role_id"), table_name="operator_role_map")
    op.drop_index(
        op.f("ix_operator_role_map_operator_id"), table_name="operator_role_map"
    )
    op.drop_index(
        op.f("ix_operator_role_map_company_id"), table_name="operator_role_map"
    )
    op.drop_table("operator_role_map")
    op.drop_index(op.f("ix_operator_image_operator_id"), table_name="operator_image")
    op.drop_index(op.f("ix_operator_image_company_id"), table_name="operator_image")
    op.drop_table("operator_image")
    op.drop_index(op.f("ix_vendor_role_business_id"), table_name="vendor_role")
    op.drop_table("vendor_role")
    op.drop_index(op.f("ix_vendor_business_id"), table_name="vendor")
    op.drop_table("vendor")
    op.drop_index(op.f("ix_operator_role_company_id"), table_name="operator_role")
    op.drop_table("operator_role")
    op.drop_index(op.f("ix_operator_company_id"), table_name="operator")
    op.drop_table("operator")

    op.drop_index(op.f("ix_company_wallet_wallet_id"), table_name="company_wallet")
    op.drop_index(op.f("ix_company_wallet_company_id"), table_name="company_wallet")
    op.drop_table("company_wallet")
    op.drop_index(
        op.f("ix_company_bank_account_company_id"), table_name="company_bank_account"
    )
    op.drop_index(
        op.f("ix_company_bank_account_bank_account_id"),
        table_name="company_bank_account",
    )
    op.drop_table("company_bank_account")
    op.drop_index(op.f("ix_business_wallet_wallet_id"), table_name="business_wallet")
    op.drop_index(op.f("ix_business_wallet_business_id"), table_name="business_wallet")
    op.drop_table("business_wallet")
    op.drop_index(
        op.f("ix_business_bank_account_business_id"), table_name="business_bank_account"
    )
    op.drop_index(
        op.f("ix_business_bank_account_bank_account_id"),
        table_name="business_bank_account",
    )
    op.drop_table("business_bank_account")

    op.drop_table("wallet")
    op.drop_geospatial_index(
        "idx_business_location",
        table_name="business",
        postgresql_using="gist",
        column_name="location",
    )
    op.drop_geospatial_table("business")
    op.drop_table("bank_account")
    # ### end Alembic commands ###
