"""modify service location columns

Revision ID: 0293fae9f3ec
Revises: fde5a9d63762
Create Date: 2026-06-06 04:20:52.240974

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0293fae9f3ec"
down_revision: Union[str, Sequence[str], None] = "fde5a9d63762"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_service_location_operator_id"), table_name="service_location"
    )
    op.drop_constraint(
        op.f("service_location_service_id_operator_id_key"),
        "service_location",
        type_="unique",
    )
    op.drop_index(op.f("ix_service_location_service_id"), table_name="service_location")
    op.create_index(
        op.f("ix_service_location_service_id"),
        "service_location",
        ["service_id"],
        unique=True,
    )
    op.drop_constraint(
        op.f("service_location_operator_id_fkey"),
        "service_location",
        type_="foreignkey",
    )
    op.drop_column("service_location", "operator_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_location",
        sa.Column("operator_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("service_location_operator_id_fkey"),
        "service_location",
        "operator",
        ["operator_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_service_location_service_id"), table_name="service_location")
    op.create_index(
        op.f("ix_service_location_service_id"),
        "service_location",
        ["service_id"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("service_location_service_id_operator_id_key"),
        "service_location",
        ["service_id", "operator_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_service_location_operator_id"),
        "service_location",
        ["operator_id"],
        unique=False,
    )
    # ### end Alembic commands ###
