"""initial schema

Revision ID: 166e2683e5fc
Revises: 
Create Date: 2026-05-07 09:31:01.931605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '166e2683e5fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.TEXT(), nullable=False),
    sa.Column('branch_name', sa.TEXT(), nullable=True),
    sa.Column('account_number', sa.TEXT(), nullable=False),
    sa.Column('holder_name', sa.TEXT(), nullable=False),
    sa.Column('ifsc', sa.TEXT(), nullable=False),
    sa.Column('account_type', sa.Integer(), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_geospatial_index('idx_business_location', 'business', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_geospatial_index('idx_company_location', 'company', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('executive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.TEXT(), nullable=True),
    sa.Column('designation', sa.TEXT(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.TEXT(), nullable=True),
    sa.Column('email_id', sa.TEXT(), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('executive_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fare_in_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fare_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('function', sa.TEXT(), nullable=False),
    sa.Column('reference_count', sa.Integer(), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fare_id', 'version')
    )
    op.create_index(op.f('ix_fare_in_service_fare_id'), 'fare_in_service', ['fare_id'], unique=False)
    op.create_geospatial_table('landmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('alias_names', sa.ARRAY(sa.String(length=32)), nullable=True),
    sa.Column('boundary', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_landmark_alias_names_gin', 'landmark', ['alias_names'], unique=False, postgresql_using='gin')
    op.create_geospatial_index('ix_landmark_boundary_gist', 'landmark', ['boundary'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_landmark_name'), 'landmark', ['name'], unique=False)
    op.create_index(op.f('ix_landmark_type'), 'landmark', ['type'], unique=False)
    op.create_index('ux_landmark_boundary_hash', 'landmark', [sa.literal_column('md5(ST_AsEWKB(boundary))')], unique=True, postgresql_using='btree')
    op.create_table('vehicle_in_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('reference_count', sa.Integer(), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'version')
    )
    op.create_index(op.f('ix_vehicle_in_service_vehicle_id'), 'vehicle_in_service', ['vehicle_id'], unique=False)
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_wallet_balance_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_table('bus_stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('landmark_id', sa.Integer(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmark.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_bus_stop_location', 'bus_stop', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_bus_stop_landmark_id'), 'bus_stop', ['landmark_id'], unique=False)
    op.create_index('uq_bus_stop_location_landmark_id', 'bus_stop', [sa.literal_column('ST_AsBinary(location)'), 'landmark_id'], unique=True)
    op.create_table('business_bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_bank_account_bank_account_id'), 'business_bank_account', ['bank_account_id'], unique=True)
    op.create_index(op.f('ix_business_bank_account_business_id'), 'business_bank_account', ['business_id'], unique=False)
    op.create_table('business_wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_wallet_business_id'), 'business_wallet', ['business_id'], unique=True)
    op.create_index(op.f('ix_business_wallet_wallet_id'), 'business_wallet', ['wallet_id'], unique=False)
    op.create_table('company_bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_bank_account_bank_account_id'), 'company_bank_account', ['bank_account_id'], unique=True)
    op.create_index(op.f('ix_company_bank_account_company_id'), 'company_bank_account', ['company_id'], unique=False)
    op.create_table('company_wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_wallet_company_id'), 'company_wallet', ['company_id'], unique=True)
    op.create_index(op.f('ix_company_wallet_wallet_id'), 'company_wallet', ['wallet_id'], unique=False)
    op.create_table('executive_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executive_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=128), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['executive_id'], ['executive.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executive_image_executive_id'), 'executive_image', ['executive_id'], unique=True)
    op.create_table('executive_role_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('executive_id', sa.Integer(), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['executive_id'], ['executive.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['executive_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'executive_id')
    )
    op.create_index(op.f('ix_executive_role_map_executive_id'), 'executive_role_map', ['executive_id'], unique=False)
    op.create_index(op.f('ix_executive_role_map_role_id'), 'executive_role_map', ['role_id'], unique=False)
    op.create_table('executive_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executive_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('refresh_token', sa.String(length=64), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('refresh_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('platform_type', sa.Integer(), nullable=True),
    sa.Column('client_details', sa.TEXT(), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['executive_id'], ['executive.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index(op.f('ix_executive_token_executive_id'), 'executive_token', ['executive_id'], unique=False)
    op.create_table('fare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('function', sa.TEXT(), nullable=False),
    sa.Column('scope', sa.Integer(), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fare_name_company_unique', 'fare', ['name', 'company_id'], unique=True, postgresql_where=sa.text('company_id IS NOT NULL'))
    op.create_index('ix_fare_name_global_unique', 'fare', ['name'], unique=True, postgresql_where=sa.text('company_id IS NULL'))
    op.create_table('operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.TEXT(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.TEXT(), nullable=True),
    sa.Column('email_id', sa.TEXT(), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'company_id')
    )
    op.create_index(op.f('ix_operator_company_id'), 'operator', ['company_id'], unique=False)
    op.create_table('operator_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name')
    )
    op.create_index(op.f('ix_operator_role_company_id'), 'operator_role', ['company_id'], unique=False)
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4096), nullable=False),
    sa.Column('start_time', sa.Time(timezone=True), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'company_id')
    )
    op.create_index(op.f('ix_route_company_id'), 'route', ['company_id'], unique=False)
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('fare_in_service_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_in_service_id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=16), nullable=False),
    sa.Column('ticket_mode', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('starting_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ending_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('starting_landmark_id', sa.Integer(), nullable=False),
    sa.Column('ending_landmark_id', sa.Integer(), nullable=False),
    sa.Column('private_key', sa.TEXT(), nullable=False),
    sa.Column('public_key', sa.TEXT(), nullable=False),
    sa.Column('remark', sa.TEXT(), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['ending_landmark_id'], ['landmark.id'], ),
    sa.ForeignKeyConstraint(['fare_in_service_id'], ['fare_in_service.id'], ),
    sa.ForeignKeyConstraint(['starting_landmark_id'], ['landmark.id'], ),
    sa.ForeignKeyConstraint(['vehicle_in_service_id'], ['vehicle_in_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_company_id'), 'service', ['company_id'], unique=False)
    op.create_index(op.f('ix_service_registration_number'), 'service', ['registration_number'], unique=False)
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('manufactured_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('insurance_upto', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pollution_upto', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fitness_upto', sa.DateTime(timezone=True), nullable=True),
    sa.Column('road_tax_upto', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number', 'company_id')
    )
    op.create_index(op.f('ix_vehicle_company_id'), 'vehicle', ['company_id'], unique=False)
    op.create_index(op.f('ix_vehicle_name'), 'vehicle', ['name'], unique=False)
    op.create_index(op.f('ix_vehicle_registration_number'), 'vehicle', ['registration_number'], unique=False)
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.TEXT(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.TEXT(), nullable=True),
    sa.Column('email_id', sa.TEXT(), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'business_id')
    )
    op.create_index(op.f('ix_vendor_business_id'), 'vendor', ['business_id'], unique=False)
    op.create_table('vendor_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name')
    )
    op.create_index(op.f('ix_vendor_role_business_id'), 'vendor_role', ['business_id'], unique=False)
    op.create_table('duty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('started_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collection', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duty_company_id'), 'duty', ['company_id'], unique=False)
    op.create_index(op.f('ix_duty_operator_id'), 'duty', ['operator_id'], unique=False)
    op.create_index(op.f('ix_duty_service_id'), 'duty', ['service_id'], unique=False)
    op.create_table('landmark_in_route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('landmark_id', sa.Integer(), nullable=False),
    sa.Column('distance_from_start', sa.Integer(), nullable=False),
    sa.Column('arrival_delta', sa.Integer(), nullable=False),
    sa.Column('departure_delta', sa.Integer(), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmark.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'distance_from_start')
    )
    op.create_index(op.f('ix_landmark_in_route_company_id'), 'landmark_in_route', ['company_id'], unique=False)
    op.create_index(op.f('ix_landmark_in_route_landmark_id'), 'landmark_in_route', ['landmark_id'], unique=False)
    op.create_index(op.f('ix_landmark_in_route_route_id'), 'landmark_in_route', ['route_id'], unique=False)
    op.create_table('landmark_in_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('landmark_id', sa.Integer(), nullable=False),
    sa.Column('distance_from_start', sa.Integer(), nullable=False),
    sa.Column('arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landmark_in_service_landmark_id'), 'landmark_in_service', ['landmark_id'], unique=False)
    op.create_index(op.f('ix_landmark_in_service_service_id'), 'landmark_in_service', ['service_id'], unique=False)
    op.create_table('operator_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=128), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_image_company_id'), 'operator_image', ['company_id'], unique=False)
    op.create_index(op.f('ix_operator_image_operator_id'), 'operator_image', ['operator_id'], unique=True)
    op.create_table('operator_role_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['operator_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'role_id', 'operator_id')
    )
    op.create_index(op.f('ix_operator_role_map_company_id'), 'operator_role_map', ['company_id'], unique=False)
    op.create_index(op.f('ix_operator_role_map_operator_id'), 'operator_role_map', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_role_map_role_id'), 'operator_role_map', ['role_id'], unique=False)
    op.create_table('operator_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('refresh_token', sa.String(length=64), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('refresh_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('platform_type', sa.Integer(), nullable=True),
    sa.Column('client_details', sa.TEXT(), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index(op.f('ix_operator_token_company_id'), 'operator_token', ['company_id'], unique=False)
    op.create_index(op.f('ix_operator_token_operator_id'), 'operator_token', ['operator_id'], unique=False)
    op.create_table('service_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'operator_id')
    )
    op.create_index(op.f('ix_service_assignment_company_id'), 'service_assignment', ['company_id'], unique=False)
    op.create_index(op.f('ix_service_assignment_operator_id'), 'service_assignment', ['operator_id'], unique=False)
    op.create_index(op.f('ix_service_assignment_service_id'), 'service_assignment', ['service_id'], unique=False)
    op.create_geospatial_table('service_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('landmark_id', sa.Integer(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmark.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'operator_id')
    )
    op.create_geospatial_index('idx_service_location_location', 'service_location', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_service_location_company_id'), 'service_location', ['company_id'], unique=False)
    op.create_index(op.f('ix_service_location_operator_id'), 'service_location', ['operator_id'], unique=False)
    op.create_index(op.f('ix_service_location_service_id'), 'service_location', ['service_id'], unique=False)
    op.create_table('vehicle_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=128), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_image_company_id'), 'vehicle_image', ['company_id'], unique=False)
    op.create_index(op.f('ix_vehicle_image_vehicle_id'), 'vehicle_image', ['vehicle_id'], unique=True)
    op.create_table('vendor_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=128), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_image_business_id'), 'vendor_image', ['business_id'], unique=False)
    op.create_index(op.f('ix_vendor_image_vendor_id'), 'vendor_image', ['vendor_id'], unique=True)
    op.create_table('vendor_role_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['vendor_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'role_id', 'vendor_id')
    )
    op.create_index(op.f('ix_vendor_role_map_business_id'), 'vendor_role_map', ['business_id'], unique=False)
    op.create_index(op.f('ix_vendor_role_map_role_id'), 'vendor_role_map', ['role_id'], unique=False)
    op.create_index(op.f('ix_vendor_role_map_vendor_id'), 'vendor_role_map', ['vendor_id'], unique=False)
    op.create_table('vendor_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('refresh_token', sa.String(length=64), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('refresh_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('platform_type', sa.Integer(), nullable=True),
    sa.Column('client_details', sa.TEXT(), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index(op.f('ix_vendor_token_business_id'), 'vendor_token', ['business_id'], unique=False)
    op.create_index(op.f('ix_vendor_token_vendor_id'), 'vendor_token', ['vendor_id'], unique=False)
    op.create_table('paper_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('duty_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ticket', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['duty_id'], ['duty.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_ticket_company_id'), 'paper_ticket', ['company_id'], unique=False)
    op.create_index(op.f('ix_paper_ticket_duty_id'), 'paper_ticket', ['duty_id'], unique=False)
    op.create_index(op.f('ix_paper_ticket_service_id'), 'paper_ticket', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_ticket_service_id'), table_name='paper_ticket')
    op.drop_index(op.f('ix_paper_ticket_duty_id'), table_name='paper_ticket')
    op.drop_index(op.f('ix_paper_ticket_company_id'), table_name='paper_ticket')
    op.drop_table('paper_ticket')
    op.drop_index(op.f('ix_vendor_token_vendor_id'), table_name='vendor_token')
    op.drop_index(op.f('ix_vendor_token_business_id'), table_name='vendor_token')
    op.drop_table('vendor_token')
    op.drop_index(op.f('ix_vendor_role_map_vendor_id'), table_name='vendor_role_map')
    op.drop_index(op.f('ix_vendor_role_map_role_id'), table_name='vendor_role_map')
    op.drop_index(op.f('ix_vendor_role_map_business_id'), table_name='vendor_role_map')
    op.drop_table('vendor_role_map')
    op.drop_index(op.f('ix_vendor_image_vendor_id'), table_name='vendor_image')
    op.drop_index(op.f('ix_vendor_image_business_id'), table_name='vendor_image')
    op.drop_table('vendor_image')
    op.drop_index(op.f('ix_vehicle_image_vehicle_id'), table_name='vehicle_image')
    op.drop_index(op.f('ix_vehicle_image_company_id'), table_name='vehicle_image')
    op.drop_table('vehicle_image')
    op.drop_index(op.f('ix_service_location_service_id'), table_name='service_location')
    op.drop_index(op.f('ix_service_location_operator_id'), table_name='service_location')
    op.drop_index(op.f('ix_service_location_company_id'), table_name='service_location')
    op.drop_geospatial_index('idx_service_location_location', table_name='service_location', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('service_location')
    op.drop_index(op.f('ix_service_assignment_service_id'), table_name='service_assignment')
    op.drop_index(op.f('ix_service_assignment_operator_id'), table_name='service_assignment')
    op.drop_index(op.f('ix_service_assignment_company_id'), table_name='service_assignment')
    op.drop_table('service_assignment')
    op.drop_index(op.f('ix_operator_token_operator_id'), table_name='operator_token')
    op.drop_index(op.f('ix_operator_token_company_id'), table_name='operator_token')
    op.drop_table('operator_token')
    op.drop_index(op.f('ix_operator_role_map_role_id'), table_name='operator_role_map')
    op.drop_index(op.f('ix_operator_role_map_operator_id'), table_name='operator_role_map')
    op.drop_index(op.f('ix_operator_role_map_company_id'), table_name='operator_role_map')
    op.drop_table('operator_role_map')
    op.drop_index(op.f('ix_operator_image_operator_id'), table_name='operator_image')
    op.drop_index(op.f('ix_operator_image_company_id'), table_name='operator_image')
    op.drop_table('operator_image')
    op.drop_index(op.f('ix_landmark_in_service_service_id'), table_name='landmark_in_service')
    op.drop_index(op.f('ix_landmark_in_service_landmark_id'), table_name='landmark_in_service')
    op.drop_table('landmark_in_service')
    op.drop_index(op.f('ix_landmark_in_route_route_id'), table_name='landmark_in_route')
    op.drop_index(op.f('ix_landmark_in_route_landmark_id'), table_name='landmark_in_route')
    op.drop_index(op.f('ix_landmark_in_route_company_id'), table_name='landmark_in_route')
    op.drop_table('landmark_in_route')
    op.drop_index(op.f('ix_duty_service_id'), table_name='duty')
    op.drop_index(op.f('ix_duty_operator_id'), table_name='duty')
    op.drop_index(op.f('ix_duty_company_id'), table_name='duty')
    op.drop_table('duty')
    op.drop_index(op.f('ix_vendor_role_business_id'), table_name='vendor_role')
    op.drop_table('vendor_role')
    op.drop_index(op.f('ix_vendor_business_id'), table_name='vendor')
    op.drop_table('vendor')
    op.drop_index(op.f('ix_vehicle_registration_number'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_name'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_company_id'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_service_registration_number'), table_name='service')
    op.drop_index(op.f('ix_service_company_id'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_route_company_id'), table_name='route')
    op.drop_table('route')
    op.drop_index(op.f('ix_operator_role_company_id'), table_name='operator_role')
    op.drop_table('operator_role')
    op.drop_index(op.f('ix_operator_company_id'), table_name='operator')
    op.drop_table('operator')
    op.drop_index('ix_fare_name_global_unique', table_name='fare')
    op.drop_index('ix_fare_name_company_unique', table_name='fare')
    op.drop_table('fare')
    op.drop_index(op.f('ix_executive_token_executive_id'), table_name='executive_token')
    op.drop_table('executive_token')
    op.drop_index(op.f('ix_executive_role_map_role_id'), table_name='executive_role_map')
    op.drop_index(op.f('ix_executive_role_map_executive_id'), table_name='executive_role_map')
    op.drop_table('executive_role_map')
    op.drop_index(op.f('ix_executive_image_executive_id'), table_name='executive_image')
    op.drop_table('executive_image')
    op.drop_index(op.f('ix_company_wallet_wallet_id'), table_name='company_wallet')
    op.drop_index(op.f('ix_company_wallet_company_id'), table_name='company_wallet')
    op.drop_table('company_wallet')
    op.drop_index(op.f('ix_company_bank_account_company_id'), table_name='company_bank_account')
    op.drop_index(op.f('ix_company_bank_account_bank_account_id'), table_name='company_bank_account')
    op.drop_table('company_bank_account')
    op.drop_index(op.f('ix_business_wallet_wallet_id'), table_name='business_wallet')
    op.drop_index(op.f('ix_business_wallet_business_id'), table_name='business_wallet')
    op.drop_table('business_wallet')
    op.drop_index(op.f('ix_business_bank_account_business_id'), table_name='business_bank_account')
    op.drop_index(op.f('ix_business_bank_account_bank_account_id'), table_name='business_bank_account')
    op.drop_table('business_bank_account')
    op.drop_index('uq_bus_stop_location_landmark_id', table_name='bus_stop')
    op.drop_index(op.f('ix_bus_stop_landmark_id'), table_name='bus_stop')
    op.drop_geospatial_index('idx_bus_stop_location', table_name='bus_stop', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('bus_stop')
    op.drop_table('wallet')
    op.drop_index(op.f('ix_vehicle_in_service_vehicle_id'), table_name='vehicle_in_service')
    op.drop_table('vehicle_in_service')
    op.drop_index('ux_landmark_boundary_hash', table_name='landmark')
    op.drop_index(op.f('ix_landmark_type'), table_name='landmark')
    op.drop_index(op.f('ix_landmark_name'), table_name='landmark')
    op.drop_geospatial_index('ix_landmark_boundary_gist', table_name='landmark', postgresql_using='gist', column_name='boundary')
    op.drop_index('ix_landmark_alias_names_gin', table_name='landmark', postgresql_using='gin')
    op.drop_geospatial_table('landmark')
    op.drop_index(op.f('ix_fare_in_service_fare_id'), table_name='fare_in_service')
    op.drop_table('fare_in_service')
    op.drop_table('executive_role')
    op.drop_table('executive')
    op.drop_geospatial_index('idx_company_location', table_name='company', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('company')
    op.drop_geospatial_index('idx_business_location', table_name='business', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('business')
    op.drop_table('bank_account')
    # ### end Alembic commands ###
