"""added_job_table

Revision ID: 1dcddea70080
Revises: 992537973170
Create Date: 2026-06-10 11:03:20.738998

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1dcddea70080"
down_revision: Union[str, Sequence[str], None] = "992537973170"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("job_type", sa.Integer(), nullable=False),
        sa.Column("frequency_type", sa.Integer(), nullable=False),
        sa.Column("frequency", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("trigger_at", sa.Time(timezone=True), nullable=False),
        sa.Column("triggering_mode", sa.Integer(), nullable=False),
        sa.Column("next_trigger_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_trigger_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trigger_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trigger_till", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "company_id"),
    )
    op.create_index(op.f("ix_job_company_id"), "job", ["company_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_company_id"), table_name="job")
    op.drop_table("job")
    # ### end Alembic commands ###
