"""added_bus_stop_table

Revision ID: 414fedbd93c4
Revises: b55b32880392
Create Date: 2025-12-10 07:01:43.588932

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "414fedbd93c4"
down_revision: Union[str, Sequence[str], None] = "b55b32880392"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")

    op.create_geospatial_table(
        "bus_stop",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("landmark_id", sa.Integer(), nullable=False),
        sa.Column(
            "location",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["landmark_id"], ["landmark.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("location", "landmark_id"),
    )
    op.create_geospatial_index(
        "idx_bus_stop_location",
        "bus_stop",
        ["location"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_bus_stop_landmark_id"), "bus_stop", ["landmark_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bus_stop_landmark_id"), table_name="bus_stop")
    op.drop_geospatial_index(
        "idx_bus_stop_location",
        table_name="bus_stop",
        postgresql_using="gist",
        column_name="location",
    )
    op.drop_geospatial_table("bus_stop")
    # ### end Alembic commands ###
