"""added_operator_table

Revision ID: 4c82a4fdf264
Revises: a9931bfb5646
Create Date: 2026-02-03 06:34:10.256303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c82a4fdf264'
down_revision: Union[str, Sequence[str], None] = 'a9931bfb5646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.TEXT(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.TEXT(), nullable=True),
    sa.Column('email_id', sa.TEXT(), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'company_id')
    )
    op.create_index(op.f('ix_operator_company_id'), 'operator', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operator_company_id'), table_name='operator')
    op.drop_table('operator')
    # ### end Alembic commands ###
