"""updated ex_token refresh_before

Revision ID: 4cd24675b1e9
Revises: b9592064514c
Create Date: 2025-10-28 07:07:38.135726

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4cd24675b1e9"
down_revision: Union[str, Sequence[str], None] = "b9592064514c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "executive_token",
        "expires_at",
        new_column_name="refresh_before",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "executive_token",
        "refresh_before",
        new_column_name="expires_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###
