"""initial schema

Revision ID: 6b3c4c95d108
Revises: 
Create Date: 2025-10-09 06:06:37.536897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3c4c95d108'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.TEXT(), nullable=True),
    sa.Column('designation', sa.TEXT(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.TEXT(), nullable=True),
    sa.Column('email_id', sa.TEXT(), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('executive_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('permissions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('executive_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executive_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=128), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['executive_id'], ['executive.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executive_image_executive_id'), 'executive_image', ['executive_id'], unique=True)
    op.create_table('executive_role_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('executive_id', sa.Integer(), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['executive_id'], ['executive.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['executive_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'executive_id')
    )
    op.create_index(op.f('ix_executive_role_map_executive_id'), 'executive_role_map', ['executive_id'], unique=False)
    op.create_index(op.f('ix_executive_role_map_role_id'), 'executive_role_map', ['role_id'], unique=False)
    op.create_table('executive_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executive_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_type', sa.Integer(), nullable=True),
    sa.Column('client_details', sa.TEXT(), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['executive_id'], ['executive.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    op.create_index(op.f('ix_executive_token_executive_id'), 'executive_token', ['executive_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executive_token_executive_id'), table_name='executive_token')
    op.drop_table('executive_token')
    op.drop_index(op.f('ix_executive_role_map_role_id'), table_name='executive_role_map')
    op.drop_index(op.f('ix_executive_role_map_executive_id'), table_name='executive_role_map')
    op.drop_table('executive_role_map')
    op.drop_index(op.f('ix_executive_image_executive_id'), table_name='executive_image')
    op.drop_table('executive_image')
    op.drop_table('executive_role')
    op.drop_table('executive')
    # ### end Alembic commands ###
