"""added new table for job

Revision ID: ae1c88bba712
Revises: 992537973170
Create Date: 2026-06-16 11:13:26.090759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1c88bba712'
down_revision: Union[str, Sequence[str], None] = '992537973170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('job_type', sa.Integer(), nullable=False),
    sa.Column('recurrence_rule', sa.TEXT(), nullable=False),
    sa.Column('trigger_at', sa.Time(timezone=True), nullable=False),
    sa.Column('triggering_mode', sa.Integer(), nullable=False),
    sa.Column('next_trigger_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_trigger_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_till', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'company_id')
    )
    op.create_index(op.f('ix_job_company_id'), 'job', ['company_id'], unique=False)
    op.create_geospatial_index('idx_landmark_boundary', 'landmark', ['boundary'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_landmark_boundary', table_name='landmark', postgresql_using='gist', column_name='boundary')
    op.drop_index(op.f('ix_job_company_id'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
