"""added landmark table

Revision ID: b55b32880392
Revises: 0d0d1c677a5d
Create Date: 2025-11-28 10:49:25.847151

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b55b32880392"
down_revision: Union[str, Sequence[str], None] = "0d0d1c677a5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable PostGIS before creating geometry columns
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")

    op.create_geospatial_table(
        "landmark",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(32), nullable=False),
        sa.Column("alias_names", sa.ARRAY(sa.String(32)), nullable=True),
        sa.Column(
            "boundary",
            Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_geospatial_index(
        "idx_landmark_boundary",
        "landmark",
        ["boundary"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        "ix_landmark_alias_names_gin",
        "landmark",
        ["alias_names"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_landmark_name"), "landmark", ["name"], unique=False)
    op.create_index(op.f("ix_landmark_type"), "landmark", ["type"], unique=False)
    op.create_index(
        "ux_landmark_boundary_hash",
        "landmark",
        [sa.text("md5(ST_AsEWKB(boundary))")],
        unique=True,
        postgresql_using="btree",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_landmark_type"), table_name="landmark")
    op.drop_index(op.f("ix_landmark_name"), table_name="landmark")
    op.drop_index("ux_landmark_boundary_hash", table_name="landmark")
    op.drop_index(
        "ix_landmark_alias_names_gin", table_name="landmark", postgresql_using="gin"
    )
    op.drop_geospatial_index(
        "idx_landmark_boundary",
        table_name="landmark",
        postgresql_using="gist",
        column_name="boundary",
    )
    op.drop_geospatial_table("landmark")
    # ### end Alembic commands ###
