"""added operator and company notification

Revision ID: b5ef018ca9f3
Revises: ed4c4f95c4bd
Create Date: 2026-08-23 10:16:46.571025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5ef018ca9f3'
down_revision: Union[str, Sequence[str], None] = 'ed4c4f95c4bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_notification',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('operator_types', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_notification_company_id'), 'company_notification', ['company_id'], unique=False)
    op.create_table('operator_notification',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('operator_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_notification_company_id'), 'operator_notification', ['company_id'], unique=False)
    op.create_index(op.f('ix_operator_notification_operator_id'), 'operator_notification', ['operator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operator_notification_operator_id'), table_name='operator_notification')
    op.drop_index(op.f('ix_operator_notification_company_id'), table_name='operator_notification')
    op.drop_table('operator_notification')
    op.drop_index(op.f('ix_company_notification_company_id'), table_name='company_notification')
    op.drop_table('company_notification')
    # ### end Alembic commands ###
