"""updated_ex_token

Revision ID: b9592064514c
Revises: 6b3c4c95d108
Create Date: 2025-10-15 06:25:50.794936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9592064514c'
down_revision: Union[str, Sequence[str], None] = '6b3c4c95d108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "executive_token",
        sa.Column("refresh_token", sa.String(length=64), nullable=False),
    )
    op.add_column(
        "executive_token",
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
    )
    sa.UniqueConstraint("refresh_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("executive_token", "refresh_token")
    op.drop_column("executive_token", "is_revoked")
    # ### end Alembic commands ###
