"""name bus_stop unique constraint

Revision ID: d4a9920be611
Revises: 414fedbd93c4
Create Date: 2026-01-28 04:52:52.171899

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd4a9920be611'
down_revision = '414fedbd93c4'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'bus_stop_location_landmark_id_key',  # Use your actual old constraint name
        'bus_stop',
        type_='unique'
    )
    op.create_unique_constraint(
        'ux_bus_stop_location_landmark_id',
        'bus_stop',
        ['location', 'landmark_id']
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'ux_bus_stop_location_landmark_id',
        'bus_stop',
        type_='unique'
    )
    op.create_unique_constraint(
        'bus_stop_location_landmark_id_key',  # Use your actual old constraint name
        'bus_stop',
        ['location', 'landmark_id']
    )
    # ### end Alembic commands ###
