"""add_operator_token_and_operator_image_tables

Revision ID: e0ee54589690
Revises: 4c82a4fdf264
Create Date: 2026-02-04 04:51:49.933787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0ee54589690'
down_revision: Union[str, Sequence[str], None] = '4c82a4fdf264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=128), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_image_company_id'), 'operator_image', ['company_id'], unique=False)
    op.create_index(op.f('ix_operator_image_operator_id'), 'operator_image', ['operator_id'], unique=True)
    op.create_table('operator_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('refresh_token', sa.String(length=64), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('refresh_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('platform_type', sa.Integer(), nullable=True),
    sa.Column('client_details', sa.TEXT(), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index(op.f('ix_operator_token_company_id'), 'operator_token', ['company_id'], unique=False)
    op.create_index(op.f('ix_operator_token_operator_id'), 'operator_token', ['operator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operator_token_operator_id'), table_name='operator_token')
    op.drop_index(op.f('ix_operator_token_company_id'), table_name='operator_token')
    op.drop_table('operator_token')
    op.drop_index(op.f('ix_operator_image_operator_id'), table_name='operator_image')
    op.drop_index(op.f('ix_operator_image_company_id'), table_name='operator_image')
    op.drop_table('operator_image')
    # ### end Alembic commands ###
