"""added_trace_and_location_in_trace_tables

Revision ID: e139fdac07b5
Revises: 0293fae9f3ec
Create Date: 2026-06-07 05:04:15.630040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e139fdac07b5"
down_revision: Union[str, Sequence[str], None] = "0293fae9f3ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trace",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=4096), nullable=False),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["company.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "company_id"),
    )
    op.create_index(op.f("ix_trace_company_id"), "trace", ["company_id"], unique=False)
    op.create_geospatial_table(
        "location_in_trace",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trace_id", sa.Integer(), nullable=False),
        sa.Column(
            "location",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("location_type", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["trace_id"], ["trace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_geospatial_index(
        "idx_location_in_trace_location",
        "location_in_trace",
        ["location"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_location_in_trace_trace_id"),
        "location_in_trace",
        ["trace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_location_in_trace_trace_id"), table_name="location_in_trace")
    op.drop_geospatial_index(
        "idx_location_in_trace_location",
        table_name="location_in_trace",
        postgresql_using="gist",
        column_name="location",
    )
    op.drop_geospatial_table("location_in_trace")
    op.drop_index(op.f("ix_trace_company_id"), table_name="trace")
    op.drop_table("trace")
    # ### end Alembic commands ###
