"""added description for trace location

Revision ID: ed4c4f95c4bd
Revises: a967fb1fc791
Create Date: 2026-08-10 10:02:56.328912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed4c4f95c4bd'
down_revision: Union[str, Sequence[str], None] = 'a967fb1fc791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_in_trace', sa.Column('description', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location_in_trace', 'description')
    # ### end Alembic commands ###
