"""added_collection_to_service

Revision ID: fde5a9d63762
Revises: 6f9dbffe26d9
Create Date: 2026-06-01 08:06:57.188109

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fde5a9d63762"
down_revision: Union[str, Sequence[str], None] = "6f9dbffe26d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service",
        sa.Column("collection", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service", "collection")
    # ### end Alembic commands ###
