resources:
  - ../../base
  - postgis.yaml
  - redis.yaml
  - minio.yaml
  - openobserve.yaml

images:
  - name: ghcr.io/nixbug/entebus-server
    newTag: develop

patches:
  - target:
      kind: Namespace
      name: entebus
    patch: |-
      - op: replace
        path: /metadata/labels/environment
        value: dev

  - target:
      kind: Ingress
      name: entebus-ingress
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: dev-api.entebus.com
      - op: replace
        path: /spec/rules/0/host
        value: dev-api.entebus.com

  - target:
      kind: Deployment
      name: entebus-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
