apiVersion: apps/v1
kind: Deployment
metadata:
  name: openobserve
  namespace: entebus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openobserve
  template:
    metadata:
      labels:
        app: openobserve
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 2000
        runAsGroup: 2000
      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            ["sh", "-c", "chown -R 2000:2000 /data && chmod -R 775 /data"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: openobserve-data
              mountPath: /data
      containers:
        - name: openobserve
          image: public.ecr.aws/zinclabs/openobserve:latest
          ports:
            - containerPort: 5080
          env:
            - name: ZO_ROOT_USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: entebus-server-secret
                  key: OPENOBSERVE_USERNAME
            - name: ZO_ROOT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: entebus-server-secret
                  key: OPENOBSERVE_PASSWORD
            - name: ZO_DATA_PATH
              value: "/data"
          volumeMounts:
            - name: openobserve-data
              mountPath: /data
              subPath: zo-data
      volumes:
        - name: openobserve-data
          persistentVolumeClaim:
            claimName: openobserve-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: openobserve
  namespace: entebus
spec:
  selector:
    app: openobserve
  ports:
    - name: http
      port: 5080
      targetPort: 5080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openobserve-pvc
  namespace: entebus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
