apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis
  namespace: entebus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgis
          image: postgis/postgis:latest
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: entebus-server-secret
                  key: PSQL_DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: entebus-server-secret
                  key: PSQL_DB_PASSWORD
            - name: POSTGRES_DB
              value: postgis
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
      volumes:
        - name: postgres-data
          hostPath:
            path: /mnt/postgres-dev-data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: postgis
  namespace: entebus
spec:
  selector:
    app: postgis
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
